Fyle import attributes
fylein/fyle-sage-desktop-api pull request #32
Opened 2023-10-19 12:32 UTC by ruuushhh

2023-10-19 12:48 UTC, NileshPant1999 commented on apps/fyle/models.py
> +    pass
new line

2023-10-19 12:49 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +                workspace.save(update_fields=['source_synced_at'])
Always better to add line changes between each section for better readability

2023-10-19 12:50 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +            raise serializers.ValidationError()
raise Exception?

also add loggers please

Everywhere the code can break should have loggers

2023-10-19 12:51 UTC, Shwetabhk approved these changes

2023-10-19 12:57 UTC, NileshPant1999 approved these changes

2023-10-19 13:25 UTC, NileshPant1999 commented on apps/fyle/models.py
> +    Creating a dummy class to be able to user
able to use 🤣

2023-10-19 13:26 UTC, NileshPant1999 commented on apps/fyle/serializers.py
> +
can we maintain 2 line spaces accorss repo

2023-10-20 02:21 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +
+1

2023-10-20 02:22 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +            raise serializers.ValidationError()
we shouldn't raise validation error for broad exceptions, just raise exception only

2023-10-20 02:24 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +            raise serializers.ValidationError()
It is not a validation error at all right, it's an unexpected error

2023-10-20 02:28 UTC, Shwetabhk requested changes

2023-10-20 02:28 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +
Yes always 2 line spaces between all statements in the top level
there can be only 1 line change within Class functions
```python
import xyz


x = y


class ABC:
    def a():
        pass

    def b():
        pass

    def c():
        pass
```

2023-10-20 02:28 UTC, Shwetabhk commented on apps/fyle/serializers.py
> +            raise serializers.ValidationError()
Please fix it off

2023-10-20 13:49 UTC, NileshPant1999 commented on apps/fyle/urls.py
> +    path('<int:workspace_id>/import_attributes/', ImportFyleAttributesView.as_view(), name='import-fyle-attributes'),
@ruuushhh workspace_id is not needed here no ??

2023-10-23 06:01 UTC, Shwetabhk approved these changes

2023-10-25 06:56 UTC, NileshPant1999 commented on apps/workspaces/serializers.py
> +        workspace = Workspace.objects.get(pk=workspace_id)
why are we doing this @ruuushhh

2023-10-26 04:14 UTC, ruuushhh commented on apps/workspaces/serializers.py
> +        workspace = Workspace.objects.get(pk=workspace_id)
<img width="741" alt="image" src="https://github.com/fylein/fyle-sage-desktop-api/assets/66899387/607e4a4d-ace8-4a97-8d60-d047899bfb43">
to get workspace users @NileshPant1999

2023-10-26 04:33 UTC, NileshPant1999 commented on apps/workspaces/models.py
> -    auto_create_vendor = BooleanFalseField(help_text='Auto create vendor')
@ruuushhh why is this removed.

2023-10-26 10:44 UTC, Shwetabhk approved these changes

2023-10-26 11:21 UTC, merged